name: Build using CMake
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  cmake-linux-local:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v2
      - name: Update apt
        run: sudo apt update
      - name: Install ninja
        run: sudo apt install ninja-build
      - name: Configure and build
        run: scripts/local-build.sh
        working-directory: ${{ github.workspace }}
  # cmake-linux-qemu:
  #   runs-on: ubuntu-22.04
  #   timeout-minutes: 40
  #   strategy:
  #     matrix:
  #       build_props:
  #         - [
  #             "cmake-linux-riscv64",
  #             "riscv64/ubuntu:22.04"
  #         ]

  #   name: ${{ matrix.build_props[0] }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup QEMU
  #       uses: docker/setup-qemu-action@v3.0.0
  #     - name: Build cpuinfo in ${{ matrix.build_props[1] }}
  #       run: |
  #         docker run -i -v $(pwd):/cpuinfo ${{ matrix.build_props[1] }} /bin/bash -c "
  #         apt update &&
  #         apt install -y cmake git gcc g++ &&
  #         cd /cpuinfo &&
  #         scripts/local-build.sh"
